version: '3.3'  
services:   
  db:    
    image: "mcr.microsoft.com/mssql/server"  
    environment:  
      MSSQL_SA_PASSWORD: "Your_password123"   
      ACCEPT_EULA: "Y" 
    ports:
      - "1433:1433"  